services:
  audio-processing:
    build: ./audio-processing
    container_name: getmaqam-audio-processing
    restart: unless-stopped
    environment:
      API_BASE_URL: http://getmaqam-backend:8080/api
    depends_on:
      - backend
    expose:
      - "8000"
    networks:
      - internal
      - proxy-net
  
  backend:
    build: ./backend
    restart: unless-stopped
    container_name: getmaqam-backend
    environment:
      PORT: 8080
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    expose:
      - "8080"
    networks:
      - internal
      - proxy-net

networks:
  internal:
  proxy-net:
    external: true
  
