spring.application.name=demo
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/maqam_api
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'validate' ensures Java matches the SQL tables perfectly without overriding SQL
spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.show-sql=true